Added occupancy variables to tests.
The occupancy variables had not been added to tests.  Now that they are added, one of the tests does not pass.

======================================================================
FAIL: testSearchMultipleResidues (pgd_search.tests.SearchParserValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pgd/pgd_search/tests.py", line 517, in testSearchMultipleResidues
    "Multiple residue search failed on field %s  Expected result was %s  Returned result was %s"%(field, set((getattr(chainList[2], '%s'%field), )), set(getattr(x, '%s'%field) for x in Search.parse_search(search)))
AssertionError: Multiple residue search failed on field occm  Expected result was set([1.2403])  Returned result was set([1.2403, 1.2402, 1.2401, 1.2405, 1.2404])